### ISSUE TITLE
User reports bug

### ISSUE THREAD

**Issue by slightlynybbled** [slightlynybbled/engineering_notation#13]
User reported a bug:

> I have noticed that with significant=3 I occasionally see "1000fA" displayed, which presumably was rounding up from 999.xnA where x>=5

Need to investigate and disposition.

**Comment by electrokean** [comment]
I'm happy for you to assign this to me.
Either way I will look at it in the next day or two.

**Comment by slightlynybbled** [comment]
I'm not seeing this issue.  Let me know if it comes up again.
