### ISSUE TITLE
Fixed number of digits

### ISSUE THREAD

**Issue by jlgb-uoc** [slightlynybbled/engineering_notation#20]
Hi!

This is a really useful package for me that work in automated test equipment.
One really good feature would be the hability to fix not only the precision but also the quantity of number before de decimal point so we can control completely the number of output characters when working with serial terminals:

EngNumber('4.999k', precision=3, significant = 3,padding = '0')
004.999k 

EngNumber('4.999k', precision=2, significant = 2,padding = '0')
04.99k 

Padding with spaces would be the most useful for me.

That would be great!

**Comment by slightlynybbled** [comment]
I use this for test equipment as well.  My apologies for the late response.  After looking at the API, I think that this may deviate from the intent of the package.  In my own programming, I would probably use something like `zfill` or `rjust` to pad the string:

    $>en = EngNumber('5k')
    $>en_str = str(en)
    $>en_str
    '5k'
    $>en_str.zfill(3)
    '05k'
    $>en_str.rjust(10, '*')
    '********5k'
    $>en_str.rjust(10)
    '        5k'

Good luck!

j
