### ISSUE TITLE
Is there a way to display in Scientific Engineering Format 

### ISSUE THREAD

**Issue by denzchoe** [slightlynybbled/engineering_notation#21]
Apologies that I am posting this here. Wish I could have posted it on Discussion though.

## Description:
Will you be introducing a sub-class (or another class) where I do not print the quantity in character form. But rather in exponent (scientific) form.
Example 
```python
EngNumber(37112.1231233123, precision = 4)
```
#### returns
`37.1121k`

#### can it return this instead?
`37.1121E+03`

## Motivation:
We are printing the return numbers in an excel sheet (extracted from DataFrame). And when printed in excel, preferably the character doesn't mix with the numbers, else it will turn the cell into string in Excel. Hence, getting rid of the character will be very useful for Excel users. 
<br>

I have a solution which [derived from here](https://stackoverflow.com/questions/62561254/python-print-in-scientific-format-with-powers-of-ten-being-only-multiples-of-3/62561794#62561794). But was just thinking it will be more elegant if it comes from this package

**Comment by slightlynybbled** [comment]
Greetings -

If you `float(eng_num)`, I believe that you should get what you are looking for.  Good luck!

j
