### ISSUE TITLE
Abilitiy Instantantiate EngUnit (or EngNumber) with a number and a unit

### ISSUE THREAD

**Issue by jaskij** [slightlynybbled/engineering_notation#22]
What I'd like is to instantiate EngUnit using a number (passed from elsewhere in my program), and a string. Right now there are multiple possible workarounds, so this is more of a quality of life request.

For example:

```py
num = 3.53e-4
eng = EngUnit(num, 's')
print(eng)  # prints 3.53us
```

Possible workarounds:

```py
# this one is fine, but doesn't work inline, say, in function argument or list comprehension
num = 3.53e-4
eng = EngUnit(num)
eng.unit = 's'
print(eng)
```

```py
# shudder
num = 3.53e-4
eng = EngUnit(str(num) + 's')
print(eng)
```

**Comment by slightlynybbled** [comment]
Try this:

    >>> EngUnit('2m', unit='meter')
    2mmeter

**Comment by slightlynybbled** [comment]
You didn't miss it, i just added it today.  Enjoy!
