### ISSUE TITLE
Space between number and SI prefix for __repr__

### ISSUE THREAD

**Issue by james-smith-za** [slightlynybbled/engineering_notation#23]
Just want to start off by saying, very useful module, thanks for developing!

It would be slightly more useful for me if there were some facility to have a space between the number and the SI prefix.
So instead of printing `2.39G`, I'd be able to get `2.39 G`.

The motivation: I'm currently using the module to generate reports of calculations of network bandwidth, and it's a style thing in my organisation to have a space after the number and before the unit:
```
The total network bandwidth consumed is 2.39 Gb/s.
```
for instance.

After a quick eyeball of the code, I think I could probably add the functionality. Would you consider a PR?

**Comment by slightlynybbled** [comment]
No problem!  Let’s work out the api before you code. What were you thinking?

**Comment by james-smith-za** [comment]
So the idea that I initially had would have looked something like this from the user's perspective:
```python
print(f"The formatted number is {EngNumber(number, separator=' ').}
```

If it is a default throughout the program, I'd wrap it in a little helper function, something like:
```python
def eng_num(number: float) -> str:
    return EngNumber(number, separator=" ")
```

**Comment by slightlynybbled** [comment]
I would accept the PR with that API. We are on the same page. Thanks!

**Comment by james-smith-za** [comment]
I haven't forgotten, I've just been redirected with other priorities... I'll get to this soon(ish)!
