### ISSUE TITLE
[Feature Request] Formatting By Significant Figures

### ISSUE THREAD

**Issue by qrqiuren** [slightlynybbled/engineering_notation#6]
The default formatting method is `precision`, which is the digits after the decimal point, but it leads to different levels of details of different numbers. Let's say, if we set `precision=0`, the number `4.23195e-4` and `4.23195e-3` will become:
```
423u
```
and
```
4m
```
correspondingly. This is very confused on some kinds of data.

What I prefer is to print the numbers by [significant digits](https://en.wikipedia.org/wiki/Significant_figures), like:
```python
>>> eng = lambda x: EngNumber(x, significant=3)
>>> eng(4.23195e-4)
'423u'
>>> eng(4.23195e-3)
'4.23m'
```

**Comment by qrqiuren** [comment]
If the maintainer allows, I would like to submit a patch, but I don't have much time recently.

**Comment by slightlynybbled** [comment]
I see no issue with this functionality and it doesn't break anything that currently exists.  If you already have something in mind, I will gladly accept a PR and push to pypi.

**Comment by electrokean** [comment]
It doesn't look like this was ever implemented, but was exactly what I was looking for.
I've made this change myself if you'd still like a PR?

**Comment by slightlynybbled** [comment]
Yes, please!

My apologies, I have made a start or two in this direction and have never completed the effort.  If you do a PR then I can review and we can close this out.  Thank you so much!

**Comment by electrokean** [comment]
PR created.  It was a bit of a quick and dirty, but is working well for me.

**Comment by slightlynybbled** [comment]
Thank you, again!

I will wrap up and push to twine after a bit more looking, but I should have this merged and out to pypi today sometime.

**Comment by slightlynybbled** [comment]
I put some automated testing around the feature and found a bit of a bug.  Was able to fix.  Thank you, again, for the PR.  Just uploaded to pypi.

**Comment by electrokean** [comment]
Excellent.  Sorry it was late at night and I was trying to just get some ATE code working, so I didn't add the tests or run flake8.
Out of interest, which test was failing?
I have noticed that with significant=3 I occasionally see "1000fA" displayed, which presumably was rounding up from 999.xnA where x>=5.  Doesn't bother me, but it is an edge case that could be better handled.

**Comment by slightlynybbled** [comment]
None of the existing tests were breaking.  I added new testing last night to cover the new code and discovered the bug.  It looked something like this:

    > EngNum('220m', significant=2)
    2.2E+2m

I don't have test cases to cover all, but I do have it for most.  The "1000fA" that you are reporting is somewhat concerning...
