### ISSUE TITLE
Extra '.' when precision=3

### ISSUE THREAD

**Issue by poleguy** [slightlynybbled/engineering_notation#8]
This is fine:
>>> x=0.10000000149011612;x = engineering_notation.EngNumber(x); print(x)
100m
This is not:
>>> x=0.10000000149011612;x = engineering_notation.EngNumber(x,precision=3); print(x)
100.m
This is fine:
>>> x=0.10000000149011612;x = engineering_notation.EngNumber(x,precision=2); print(x)
100m
This is fine:
>>> x=0.10000000149011612;x = engineering_notation.EngNumber(x,precision=4); print(x)
100.0m

I consider this a bug, as it's not typical to leave a trailing decimal. What do you think?
Also, I think the significant figure approach suggested in another issue is mathematically more useful.

**Comment by slightlynybbled** [comment]
Agreed on both counts.  Pull requests welcome!

**Comment by poleguy** [comment]
Hey, I'm confused about why my latest commit failed CI. It passes the tests when I run them locally.  My latest commit is better than my first. sorry for the churn.
